spring:
  application:
    name: textMe
  datasource:
    url: jdbc:mysql://localhost:3306/text_me?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false