spring:
  application:
    name: textMe
  datasource:
    url: jdbc:mysql://localhost:3306/text_me?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

data:
  config:
    email: lajabu.john@outlook.com
    username: lajabu.john
    password: 123456
  token:
    signing:
      key: 413F4428472B5454584d5f5de28r9w5d6452948404D6351
    expiration: 10080 #7 days